//! Ed25519 keys, certificate fingerprints and message signing.
//!
//! One keypair per node, generated by `hivemind init`. Fingerprints are
//! rendered for humans as `hm1:<base32-lower>` with an 8-character short prefix
//! (SPEC §6.1).
//!
//! # Two representations, on purpose
//!
//! Byte-valued types here serialise as hex strings to human-readable formats
//! and as CBOR byte strings otherwise. Mail on disk is JSON that a user is
//! invited to read (`docs/decisions/0002-files-are-source-of-truth.md`), and a
//! JSON array of 32 integers is not readable; the canonical encoding that gets
//! signed wants the compact, unambiguous form instead.

use std::fmt;

use serde::de::{Unexpected, Visitor};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use sha2::{Digest as _, Sha256};

/// Serialise `bytes` as hex to human-readable formats, raw otherwise.
pub(crate) fn serialize_bytes<S: Serializer>(bytes: &[u8], s: S) -> Result<S::Ok, S::Error> {
    if s.is_human_readable() {
        s.serialize_str(&hex_encode(bytes))
    } else {
        s.serialize_bytes(bytes)
    }
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        // INVARIANT: writing to a String cannot fail, and the format is fixed
        // width, so there is nothing to handle.
        let _ = fmt::Write::write_fmt(&mut out, format_args!("{byte:02x}"));
    }
    out
}

fn hex_decode<const N: usize, E: serde::de::Error>(s: &str) -> Result<[u8; N], E> {
    if s.len() != N * 2 {
        return Err(E::invalid_length(
            s.len(),
            &"a hex string of the right length",
        ));
    }
    let mut out = [0u8; N];
    for (i, slot) in out.iter_mut().enumerate() {
        let pair = s
            .get(i * 2..i * 2 + 2)
            .ok_or_else(|| E::custom("hex string split on a character boundary"))?;
        *slot = u8::from_str_radix(pair, 16)
            .map_err(|_| E::invalid_value(Unexpected::Str(pair), &"two hex digits"))?;
    }
    Ok(out)
}

struct FixedBytes<const N: usize>;

impl<const N: usize> Visitor<'_> for FixedBytes<N> {
    type Value = [u8; N];

    fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{N} bytes, or a hex string of {} characters", N * 2)
    }

    fn visit_bytes<E: serde::de::Error>(self, v: &[u8]) -> Result<Self::Value, E> {
        <[u8; N]>::try_from(v).map_err(|_| E::invalid_length(v.len(), &self))
    }

    fn visit_byte_buf<E: serde::de::Error>(self, v: Vec<u8>) -> Result<Self::Value, E> {
        self.visit_bytes(&v)
    }

    fn visit_str<E: serde::de::Error>(self, v: &str) -> Result<Self::Value, E> {
        hex_decode::<N, E>(v)
    }
}

pub(crate) fn deserialize_bytes<'de, D: Deserializer<'de>, const N: usize>(
    d: D,
) -> Result<[u8; N], D::Error> {
    if d.is_human_readable() {
        d.deserialize_str(FixedBytes::<N>)
    } else {
        d.deserialize_bytes(FixedBytes::<N>)
    }
}

/// A SHA-256 content address: what a blob is stored and fetched by (SPEC §4.3).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Sha256Digest([u8; 32]);

impl Sha256Digest {
    /// Hash some bytes.
    #[must_use]
    pub fn of(bytes: &[u8]) -> Self {
        Self(Sha256::digest(bytes).into())
    }

    /// The raw digest.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

impl fmt::Display for Sha256Digest {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&hex_encode(&self.0))
    }
}

impl Serialize for Sha256Digest {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        serialize_bytes(&self.0, s)
    }
}

impl<'de> Deserialize<'de> for Sha256Digest {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        deserialize_bytes::<D, 32>(d).map(Self)
    }
}

/// An Ed25519 signature over a message's canonical encoding (SPEC §4.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Signature([u8; 64]);

impl Signature {
    /// Wrap raw signature bytes.
    #[must_use]
    pub fn from_bytes(bytes: [u8; 64]) -> Self {
        Self(bytes)
    }

    /// The raw signature.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 64] {
        &self.0
    }
}

impl Serialize for Signature {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        serialize_bytes(&self.0, s)
    }
}

impl<'de> Deserialize<'de> for Signature {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        deserialize_bytes::<D, 64>(d).map(Self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const NOTES_HEX: &str = "ab5aa97074c454a0632057e704220d9a6678fbf773a0a5806fc09b8173b07309";

    #[test]
    fn a_digest_displays_as_lowercase_hex() {
        assert_eq!(Sha256Digest::of(b"notes").to_string(), NOTES_HEX);
    }

    #[test]
    fn a_digest_is_hex_in_json_and_a_byte_string_in_cbor() {
        let digest = Sha256Digest::of(b"notes");

        let json = serde_json::to_string(&digest).expect("must serialise");
        assert_eq!(json, format!("\"{NOTES_HEX}\""));

        let mut cbor = Vec::new();
        ciborium::into_writer(&digest, &mut cbor).expect("must serialise");
        // 0x58 0x20 is a CBOR byte string of 32 bytes; the digest follows raw.
        assert_eq!(&cbor[..2], &[0x58, 0x20]);
        assert_eq!(&cbor[2..], digest.as_bytes());
    }

    #[test]
    fn a_digest_round_trips_through_both_encodings() {
        let digest = Sha256Digest::of(b"notes");

        let json = serde_json::to_string(&digest).expect("must serialise");
        assert_eq!(
            serde_json::from_str::<Sha256Digest>(&json).expect("must deserialise"),
            digest
        );

        let mut cbor = Vec::new();
        ciborium::into_writer(&digest, &mut cbor).expect("must serialise");
        assert_eq!(
            ciborium::from_reader::<Sha256Digest, _>(cbor.as_slice()).expect("must deserialise"),
            digest
        );
    }

    #[test]
    fn a_signature_round_trips_through_both_encodings() {
        let signature = Signature::from_bytes([0x5A; 64]);

        let json = serde_json::to_string(&signature).expect("must serialise");
        assert_eq!(
            serde_json::from_str::<Signature>(&json).expect("must deserialise"),
            signature
        );

        let mut cbor = Vec::new();
        ciborium::into_writer(&signature, &mut cbor).expect("must serialise");
        assert_eq!(
            ciborium::from_reader::<Signature, _>(cbor.as_slice()).expect("must deserialise"),
            signature
        );
    }

    #[test]
    fn a_digest_from_a_hex_string_of_the_wrong_length_is_rejected() {
        let truncated = format!("\"{}\"", &NOTES_HEX[..62]);
        assert!(serde_json::from_str::<Sha256Digest>(&truncated).is_err());
    }

    #[test]
    fn a_digest_containing_non_hex_characters_is_rejected() {
        let corrupted = format!("\"zz{}\"", &NOTES_HEX[2..]);
        assert!(serde_json::from_str::<Sha256Digest>(&corrupted).is_err());
    }

    #[test]
    fn a_digest_whose_hex_splits_a_multibyte_character_is_rejected() {
        // 64 bytes of UTF-8 that is not 64 characters: the naive `s.len()`
        // check passes and the byte-pair slicing must not panic.
        let sneaky = format!("\"{}\"", "é".repeat(32));
        assert!(serde_json::from_str::<Sha256Digest>(&sneaky).is_err());
    }

    #[test]
    fn a_cbor_byte_string_of_the_wrong_length_is_rejected() {
        let mut cbor = Vec::new();
        ciborium::into_writer(&serde_bytes_helper([0u8; 16]), &mut cbor).expect("must serialise");
        assert!(ciborium::from_reader::<Sha256Digest, _>(cbor.as_slice()).is_err());
    }

    /// Serialises a fixed array as a CBOR byte string, which `[u8; N]` does not
    /// do by default.
    fn serde_bytes_helper<const N: usize>(bytes: [u8; N]) -> impl Serialize {
        struct Raw<const N: usize>([u8; N]);
        impl<const N: usize> Serialize for Raw<N> {
            fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
                s.serialize_bytes(&self.0)
            }
        }
        Raw(bytes)
    }
}
