//! Ed25519 keys, certificate fingerprints and message signing.
//!
//! One keypair per node, generated by `hivemind init`. Fingerprints are
//! rendered for humans as `hm1:<base32-lower>` with an 8-character short prefix
//! (SPEC §6.1).
